"""Stage 2: topology assembly + residue reordering.

GROMACS requires [molecules] to list species in the order atoms appear in the
.gro, with counts. So we (a) reorder residues to make each species contiguous,
and (b) emit topol.top with matching counts, a merged [atomtypes] union across
components, and each component's bonded params.
"""

from __future__ import annotations

from collections import OrderedDict
from typing import Dict, List, Optional, Tuple

from .core.gro import GroStructure, read_gro, write_gro
from .core.topfile import TopFile, parse_top


def reorder_by_residue(struct: GroStructure, order: List[str]) -> Tuple[GroStructure, Dict[str, int]]:
    """Group atoms so all residues of each resname are contiguous, in `order`.

    Returns the reordered structure and per-resname residue counts (for
    [molecules]). Residue identity is tracked by (resid, resname) runs so we
    don't merge distinct residues that share a name.
    """
    # Split atoms into residue blocks preserving original sequence.
    blocks: List[Tuple[int, str, list]] = []
    cur_key = None
    for atom in struct.atoms:
        key = (atom.resid, atom.resname)
        if key != cur_key:
            blocks.append((atom.resid, atom.resname, []))
            cur_key = key
        blocks[-1][2].append(atom)

    counts: Dict[str, int] = {name: 0 for name in order}
    new_atoms = []
    new_resid = 0
    new_atomnum = 0
    for name in order:
        for _, resname, block in blocks:
            if resname != name:
                continue
            new_resid += 1
            counts[name] += 1
            for atom in block:
                new_atomnum += 1
                a = type(atom)(new_resid, atom.resname, atom.atomname,
                               new_atomnum, atom.x, atom.y, atom.z, atom.vel)
                new_atoms.append(a)

    out = GroStructure(title=struct.title + " (reordered)", atoms=new_atoms, box=struct.box)
    return out, counts


def merge_topfiles(sources: Dict[str, str]) -> Tuple[TopFile, List[str]]:
    """Parse and merge component topology sources into one TopFile.

    sources: resname -> path to a .itp/.top defining that molecule (it may also
    define others via #include; extras are pooled and deduped). Returns the
    merged TopFile and a list of human-readable warnings (e.g. atomtype clashes).
    """
    merged = TopFile()
    warnings: List[str] = []
    for path in dict.fromkeys(sources.values()):  # unique sources, in order
        tf = parse_top(path)
        if tf.defaults and not merged.defaults:
            merged.defaults = tf.defaults
        elif tf.defaults and _norm(tf.defaults) != _norm(merged.defaults):
            warnings.append(f"[defaults] in {path} differs from the first; kept first")
        for name, line in tf.atomtypes.items():
            if name in merged.atomtypes and _norm([merged.atomtypes[name]]) != _norm([line]):
                warnings.append(f"atomtype {name!r} defined differently in {path}; kept first")
            merged.atomtypes.setdefault(name, line)
        for name, block in tf.molecules.items():
            merged.molecules.setdefault(name, block)
    return merged, warnings


def assemble_topology(surface_gro: str, itp_map: Dict[str, str], order: List[str],
                      out_top: str, out_gro: Optional[str] = None,
                      validate: bool = False, mdp: Optional[str] = None) -> Dict[str, int]:
    """Write a simulation-ready topol.top for `surface_gro`.

    itp_map: resname -> source .itp/.top. order: resnames in [molecules] order.
    Returns per-resname counts. With validate=True, runs `gmx grompp` as a gate.
    """
    struct = read_gro(surface_gro)
    reordered, counts = reorder_by_residue(struct, order)
    if out_gro:
        write_gro(reordered, out_gro)

    merged, warnings = merge_topfiles(itp_map)
    for w in warnings:
        print(f"warning: {w}")

    # Every requested molecule must have a definition and resolvable atom types.
    missing_mol = [n for n in order if n not in merged.molecules]
    if missing_mol:
        raise ValueError(f"no [moleculetype] found for: {missing_mol}")
    for name in order:
        unknown = [t for t in merged.atomtype_names_used(name)
                   if t not in merged.atomtypes]
        if unknown:
            raise ValueError(
                f"molecule {name!r} uses atom types not in any [atomtypes]: "
                f"{sorted(set(unknown))}. Supply a source that defines them."
            )

    lines: List[str] = ["; topol.top generated by samgen", ""]
    lines += merged.defaults or [
        "[ defaults ]",
        "; nbfunc  comb-rule  gen-pairs  fudgeLJ  fudgeQQ",
        "1         2          yes        0.5      0.8333",
    ]
    lines.append("")
    lines.append("[ atomtypes ]")
    lines.extend(merged.atomtypes.values())
    lines.append("")
    for name in order:
        lines.extend(merged.molecules[name])
        lines.append("")
    lines += ["[ system ]", "SAM surface", "", "[ molecules ]",
              "; Compound        nmols"]
    for name in order:
        lines.append(f"{name:<16s} {counts[name]}")
    with open(out_top, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    _print_runready_notice()

    if validate:
        _validate(out_top, out_gro or surface_gro, mdp)

    return counts


def _print_runready_notice() -> None:
    """Remind the user of the two run-readiness steps samgen leaves to them.

    samgen builds geometry and topology but deliberately does not add position
    restraints or center the box: both are simulation-setup choices the user
    owns. We print a reminder rather than silently omitting them.
    """
    print(
        "\n"
        "note: topol.top written. Two steps remain YOUR responsibility before\n"
        "      running MD (samgen does not do these):\n"
        "  1. Position restraints — restrain the anchor sulfur (and typically\n"
        "     the 7th chain carbon) so the SAM stays anchored. Add a\n"
        "     [ position_restraints ] block / #ifdef POSRES to each component\n"
        "     .itp and define POSRES in your .mdp.\n"
        "  2. Center/box the structure — run e.g.\n"
        "       gmx editconf -f <surface>.gro -o centered.gro -c -d <pad>\n"
        "     to set the final periodic box before solvation/equilibration.\n"
    )


def _validate(top: str, gro: str, mdp: Optional[str]) -> None:
    """Run gmx grompp as an acceptance gate; raise on failure."""
    from . import gmx
    import os, tempfile

    if not gmx.available():
        print("warning: GROMACS not found; skipping grompp validation")
        return
    if mdp is None:  # a minimal mdp is enough for a topology/coordinate check
        fd, mdp = tempfile.mkstemp(suffix=".mdp")
        os.write(fd, b"integrator = md\nnsteps = 0\n")
        os.close(fd)
    res = gmx.grompp(top, gro, mdp)
    if res.returncode != 0:
        raise RuntimeError("gmx grompp rejected the topology:\n" + res.stderr[-2000:])
    print("gmx grompp: topology OK")


def _norm(lines: List[str]) -> List[str]:
    """Normalise whitespace/comments for comparing topology fragments."""
    return [" ".join(l.split(";", 1)[0].split()) for l in lines
            if l.split(";", 1)[0].strip()]
